### ISSUE TITLE
bugs in genbank_to_virulign.py

### ISSUE THREAD

**Issue by thierryjanssens** [rega-cev/virulign-tutorial#1]
Hello I experience some bugs in using genbank_to_virulign.py.

$ python virulign-tools/annotations/genbank_to_virulign.py entero_rhino/NC_002058.3.xml VP1 2480 3385
# run from a jupyter notebook (bash kernel)

At first I get errors on lacking parentheses when using print )I have edited myself.)
Then I get the following error:
 Traceback (most recent call last):
  File "virulign-tools/annotations/genbank_to_virulign.py", line 19, in <module>
    sequence = doc.find('.' + sequence_prefix).text
AttributeError: 'NoneType' object has no attribute 'text'

Kind regards,

Thierry

**Comment by plibin** [comment]
Dear Thierry,

thanks for this report.
From seeing your error messages, I believe the problem is that you use python3, while our script is still in python2 syntax. This is not clear from the documentation, so I will improve this. However, it would probably be better to port this script to python3 altogether.

Is it possible for you to use python2, to get you going? If so, I will work on the python3 port somewhere next week. However, if this is blocking you, I will try to do this tonight.

Kind regards,

Pieter

**Comment by thierryjanssens** [comment]
Dear Pieter,

I acknowledge your quick responses. However, I am sorry to report the following:
Upon execution  of the script in a python2 environment the latter error remains.

python --version
python virulign-tools/annotations/genbank_to_virulign.py entero_rhino/NC_002058.3.xml VP1 2480 3385

(base-py2) (base-py2) (base-py2) Python 2.7.14
(base-py2) Traceback (most recent call last):
  File "virulign-tools/annotations/genbank_to_virulign.py", line 19, in <module>
    sequence = doc.find('.' + sequence_prefix).text
AttributeError: 'NoneType' object has no attribute 'text'
(base-py2) 

Kind regards,

Thierry

**Comment by plibin** [comment]
Dear Thierry,

I'm sorry for this inconvenience.
I tried to reproduce your problem by downloading the XML file from genbank, using "Send to >> complete record >> file >> format = insdseq xml". When I try to run the script on this XML file, it works as expected. I attached the file to this comment, could you try you can still reproduce the problem with this file, and if not, can you check whether your file is different?

Kind regards, 

Pieter
[NC_002058.3.gbc.xml.zip](https://github.com/rega-cev/virulign-tutorial/files/2348237/NC_002058.3.gbc.xml.zip)

**Comment by thierryjanssens** [comment]
Hello Pieter,

thank you for the example file. I am able to reproduce it identically, but it differs from other reference *.xml files as in the tutorial.
For example HIV-HXB2-pol.xml only contains the reference sequence and not the entire genome sequence added in front as with the poliovirus reference xml we both made.

Could this be the cause for the following error which is returned upon executing the following command?:
 (test.fas is a set of enterovirus s.l. polyprotein containg contigs sequences)
$ python genbank_to_virulign.py NC_002058.3.xml VP1 2480 3386 > NC_002058.3.conv.xml
$ virulign NC_002058.3.conv.xml test.fas \
--exportKind GlobalAlignment \
--exportAlphabet Nucleotides  > test_virulign.fas

$ Align target 0 (Rhinovirus_A__idxyz_NODE_1_1)
virulign: /path/virulign/src/libseq/AASequence.cpp:51: static seq::AASequence seq::AASequence::translate(std::vector<seq::Nucleotide>::const_iterator, std::vector<seq::Nucleotide>::const_iterator): Assertion `size % 3 == 0' failed.
Aborted

Based on this error code  I am puzzled what to do next.

kind regards,

Thierry

**Comment by thierryjanssens** [comment]
Hello Pieter,

The same happens when the HIV-1 pol  xml is prepared as follows from INSD xml freshly downloaded from NCBI.

$python genbank_to_virulign.py NC001802.1.gbc.xml pol 1655 4639 > NC001802.1.conv.xml
$ virulign NC001802.1.conv.xml chaplin2018-sequences.fasta > test2.out
Align target 0 (MF622552.1)18-sequences.fasta > virulign-tutorial/test2.out
Align target 0 (MF622552.1)
virulign: virulign/src/libseq/AASequence.cpp:51: static seq::AASequence seq::AASequence::translate(std::vector<seq::Nucleotide>::const_iterator, std::vector<seq::Nucleotide>::const_iterator): Assertion `size % 3 == 0' failed.
Aborted

The same error is reported (as with my own dataset) and the complete genome seqeunce appears in the newly prepared xml reference file.

kind regards,

Thierry

**Comment by ktheyss** [comment]
Dear Thierry. 

The output of the python script for converting a genbank xml is currently not directly usable with virulign. (Minimal) manual editing is needed to end up with a working virulign xml file.  This strategy is in place for this moment as we prefer curated and validated virulign xml files.  So in the end, some manual editing is needed, but this should be minimal.

**Comment by plibin** [comment]
Hi Thierry,

We'll have a look what goes wrong here.
The fact that virulign throws the not so informative assertion means that the number of nucleotides in the reference sequence is not a multiple of 3, and therefore not a coding sequence. 

We'll come back to you, kind regards,

Pieter

**Comment by thierryjanssens** [comment]
Hi,

genbank_to_virulign.py entero_rhino/NC_002058.3.xml VP1 2480 3386 uses the coordinates from NCBI, but do generate a reference xml file with just 605 bases. Extending it with one extra bases makes the xml unreadable after execution of virulign as above.

mxml: Missing value for attribute ',' in element orf!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing ORF reference file
Aborted

kind regards,

Thierry

**Comment by ktheyss** [comment]
Dear Thierry, our apologies for the inconvenience. Yes, the positioning is a concern at the moment. When i use the coordinates 'VP1 2480 3387' using the python script, i end up with the complete sequence for VP1 (ending with the amino acids ...TTY).  As explained above, the virulign xml needs manual editing (remove the upper sequence, remove unnecessary annotations etc), but it should work.  The discrepancy in positioning compared to the NCBI description will be addressed in updates of our tool. We thank you for noticing these issues, so we can further improve the tool.

**Comment by plibin** [comment]
Hi Thierry, 

I updated our documentation so that it is clear that we require python v2 for the genbank2virulign script. 

Were you able to generate a proper virulign XML file based on Kristof's recommendations? I created a new feature request to select the ORF based on the name of the  of the CDS in genbank: https://github.com/rega-cev/virulign-tools/issues/1. I will try to work on this issue ASAP.

Please let me know if this solves your problem, if so, I will close this issue.

Kind regards,

Pieter

**Comment by thierryjanssens** [comment]
Hi Pieter,

thank you for your helpfulness.
I succeeded preparing a proper .xml file after manual editing, after taking away the spurious annotations on the bottom (which are actually present in the HIV-1 rt example,...) and I am able to run virulign now. (Congratulations for this useful tool, amazing).

Still, it is not crystal clear how to make use of the genbank delivered coordinates in order to prepare this xml file with the provided python script. Also, the coordinates in the xml file at the bottom differ from those provided in the genbank file.

Have a nice weekend.

Thierry

**Comment by plibin** [comment]
Dear Thierry,

I think there has been some misunderstanding. At some point, we understood that you want the XML to only contain the VP1 protein? Currently, the aim for the script is to convert the complete nucleotide sequence that is associated with the particular complete ORF. Typically, you would than list all the proteins that are associated with this region.  While it is definitely possible to handcraft XML files for specific proteins, I think it is more generic to do it for the entire ORF. And you can still select specific proteins as a post processing step (one way to do this is explain in our tutorial: "Scripts to select individual proteins"). In the near future, we also plan to include a protein selection feature in virulign's command line interface.
 
Kristof made a mistake though: the command to describe the full CDS for the enterovirus reference sequence NC_002058 is python genbank_to_virulign.py NC_002058.3.gbc.xml ETV-gp1 743 7372 Where the positions 743 7370 should correspond exactly to the positions of the CDS in the genbank entry.  This is at least what _should_ happen, but there seems to be a bug in the script. We fixed this bug and pushed it to GitHub.
From your questions, it was also obvious that the documentation is not clear enough. I worked on this as well, and would be very happy if you could review my changes, to ensure they make everything clear.

Once everything is cleared out, I would be more than happy to include your polio reference XML to our git repos.  

Thanks for you invaluable remarks and kind regards,  
Pieter
